name: 'Project recognition'
description: 'Allocate labels depends on changed files'
inputs:
  label_filename:
    description: 'Filename which contain label metadata to look for'
    required: true
  owners_filename:
    description: 'Filename which contain owners metadata to look for'
    required: true
  keepers_filename:
    description: 'Filename which contain keepers metadata to look for'
    required: true
  token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: target
  color: gray-dark
