name: 'Project recognition'
description: 'Allocate labels depends on changed files'
inputs:
  label_filename:
    description: 'Filename which contain label metadata to look for'
    required: true
  owners_filename:
    description: 'Filename which contain owners metadata to look for'
    required: true
  ignore_files:
    description: 'Files to be ignored when assigning reviewers'
    required: false
  workflow_filename:
    description: 'The filename of the current action'
    required: true
  token:
    description: 'GitHub token'
    required: true
  branch_name:
    description: 'Name of the Branch'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: target
  color: gray-dark
